### ISSUE TITLE
doesn't find any results

### ISSUE THREAD

**Issue by YobiMyszkowski** [Frizz925/gbf-desktop-raidfinder#1]
Hi there. 

I made twitter app, created twitter env. with key and secret.
Authorized it.
Everything go smooth but after i pick up raid it cant find anything.

https://i.imgur.com/srok0xZ.png

What am i missing? :/

**Comment by frizz925** [comment]
This project was last maintained back in 2017, the raid tweet format has changed since then. Sorry, but this project has been long abandoned.
